### ISSUE TITLE
Not compatible with symfony/webpack-encore 2.0+

### ISSUE THREAD

**Issue by pdhuaman** [Arkounay/ux-collection#3]
Just upgraded to the latest webpack-encore release and this package is the only one giving me issues. Anybody else with the same issue? I know this update is a major release, and there are a lot of breaking points, but is there any plans to update this package to be compatible with the latest webpack-encore release?

**Comment by Arkounay** [comment]
Hi, yes there are plans to keep this package up to date.  Tomorrow probably I'll check what changed with webpack encore and make a new release

**Comment by Arkounay** [comment]
I've made a new fresh project to test with `symfony new project --webapp` using `@symfony/webpack-encore": "^2.1.0"` in `package.json` and `"symfony/webpack-encore-bundle": "^1.14",` in `composer.json` (they are the latests releases afaik) and everything seems to be working.
Do you have an error message?

**Comment by pdhuaman** [comment]
I get the following:

`./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[1].use[1]!./node_modules/@arkounay/ux-collection/src/style-when-not-using-bootstrap-5.css" contains a reference to the file "../../../css-loader/dist/runtime/cssWithMappingToString.js`

It seems that since the css-loader got updated, the reference to that file got broken. Can you share your package.json? I would like to see what versions you using.

**Comment by Arkounay** [comment]
Here's my package.json

```
{
    "devDependencies": {
        "@arkounay/ux-collection": "file:vendor/arkounay/ux-collection/Resources/assets",
        "@hotwired/stimulus": "^3.0.0",
        "@symfony/stimulus-bridge": "^3.0.0",
        "@symfony/webpack-encore": "^2.0.0",
        "core-js": "^3.0.0",
        "regenerator-runtime": "^0.13.2",
        "sass": "^1.51.0",
        "sass-loader": "^12.0.0",
        "sortablejs": "^1.14.0",
        "webpack-notifier": "^1.6.0"
    },
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
        "dev-server": "encore dev-server",
        "dev": "encore dev",
        "watch": "encore dev --watch",
        "build": "encore production --progress"
    }
}
```

**Comment by pdhuaman** [comment]
Fully removed sass-loader (12.6.0) and installed 12.0.0 and the problem is gone. Wondering what went wrong though. 12.6 has no major changes. Anyways thanks for the help.

**Comment by Arkounay** [comment]
Strange, because my sass-loader in node_module is 12.6.0
Oh well, glad it works :+1:
